export const installCommands = {
  powershell: [
    "git clone https://github.com/anikeaty08/MELD.git",
    "cd MELD",
    "python -m venv .venv",
    ".\\.venv\\Scripts\\Activate.ps1",
    "python -m pip install --upgrade pip",
    "python -m pip install .",
    "python -m meld.bootstrap --datasets CIFAR-10 CIFAR-100 --data-root ./data",
  ].join("\n"),
  cmd: [
    "git clone https://github.com/anikeaty08/MELD.git",
    "cd MELD",
    "python -m venv .venv",
    ".venv\\Scripts\\activate.bat",
    "python -m pip install --upgrade pip",
    "python -m pip install .",
    "python -m meld.bootstrap --datasets CIFAR-10 CIFAR-100 --data-root ./data",
  ].join("\n"),
  unix: [
    "git clone https://github.com/anikeaty08/MELD.git",
    "cd MELD",
    "python3 -m venv .venv",
    "source .venv/bin/activate",
    "python -m pip install --upgrade pip",
    "python -m pip install .",
    "python -m meld.bootstrap --datasets CIFAR-10 CIFAR-100 --data-root ./data",
  ].join("\n"),
  docs: [
    "cd docs-site",
    "npm install",
    "npm run dev",
  ].join("\n"),
};

export const examples = {
  syntheticCompare: [
    "python -m meld.cli \\",
    "  --dataset synthetic \\",
    "  --num-tasks 2 \\",
    "  --classes-per-task 2 \\",
    "  --run-mode compare \\",
    "  --epochs 1 \\",
    "  --batch-size 8 \\",
    "  --backbone resnet20 \\",
    "  --num-workers 0 \\",
    "  --results-path results_repo_smoke.json",
  ].join("\n"),
  cifar10: [
    "python -m meld.cli \\",
    "  --dataset CIFAR-10 \\",
    "  --num-tasks 5 \\",
    "  --classes-per-task 2 \\",
    "  --epochs 5 \\",
    "  --batch-size 64 \\",
    "  --lr 0.01 \\",
    "  --num-workers 0 \\",
    "  --results-path results_cifar10.json",
  ].join("\n"),
  text: [
    "python -m meld.cli \\",
    "  --dataset AGNews \\",
    "  --num-tasks 1 \\",
    "  --classes-per-task 4 \\",
    "  --epochs 1 \\",
    "  --batch-size 8 \\",
    "  --backbone text_encoder \\",
    "  --text-encoder-model sentence-transformers/all-MiniLM-L6-v2 \\",
    "  --num-workers 0 \\",
    "  --results-path results_agnews.json",
  ].join("\n"),
  provider: [
    "from torch.utils.data import TensorDataset",
    "import torch",
    "",
    "from meld import MELDConfig, TrainConfig, register_dataset, run",
    "from meld.datasets import split_classification_dataset_into_tasks",
    "",
    "def my_provider(config: MELDConfig):",
    "    train = TensorDataset(",
    "        torch.randn(12, 3, 32, 32),",
    "        torch.tensor([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),",
    "    )",
    "    test = TensorDataset(",
    "        torch.randn(8, 3, 32, 32),",
    "        torch.tensor([0, 0, 1, 1, 2, 2, 3, 3]),",
    "    )",
    "    return split_classification_dataset_into_tasks(",
    "        train,",
    "        test,",
    "        num_tasks=config.num_tasks,",
    "        classes_per_task=config.classes_per_task,",
    "    )",
    "",
    "register_dataset('CustomImages', my_provider, overwrite=True)",
    "",
    "results = run(",
    "    MELDConfig(",
    "        dataset='CustomImages',",
    "        num_tasks=2,",
    "        classes_per_task=2,",
    "        train=TrainConfig(backbone='resnet20', epochs=3, batch_size=16),",
    "    ),",
    "    results_path='custom_results.json',",
    ")",
  ].join("\n"),
  deltaModel: [
    "import torch",
    "from torch.utils.data import DataLoader, TensorDataset",
    "",
    "from meld.delta import DeltaModel",
    "from meld.api import TrainConfig",
    "",
    "task0 = DataLoader(",
    "    TensorDataset(torch.randn(24, 3, 32, 32), torch.tensor([0] * 12 + [1] * 12)),",
    "    batch_size=8,",
    "    shuffle=True,",
    ")",
    "",
    "model = DeltaModel.from_scratch(",
    "    backbone='resnet20',",
    "    train_config=TrainConfig(epochs=2, batch_size=8, lr=0.01),",
    ")",
    "",
    "result = model.update(task0)",
    "print(result)",
    "model.save('delta_model.pt')",
  ].join("\n"),
};

export const researchCards = [
  {
    title: "Sugiyama et al. - importance weighting",
    citation: "Direct density ratio ideas behind reweighting new-task loss.",
    usage:
      "MELD uses importance weighting to reduce the bias introduced by training only on new data instead of the full historical distribution.",
  },
  {
    title: "Cortes et al. - learning bounds",
    citation: "Generalization analysis for importance-weighted learning.",
    usage:
      "The oracle reports PAC-style gap terms next to the empirical spectral risk estimate so MELD can separate heuristic risk from theorem-backed concentration terms.",
  },
  {
    title: "Kirkpatrick et al. - EWC",
    citation: "Fisher information as a quadratic penalty for preserving old knowledge.",
    usage:
      "The GeometryConstrainedUpdater keeps an EWC term built from FisherManifoldSnapshot to stabilize old-task parameters while learning the new task.",
  },
  {
    title: "Buzzega et al. - DER++",
    citation: "A strong replay baseline continual-learning papers still compare against.",
    usage:
      "MELD keeps compare-mode reporting and baseline hooks so delta updates are measured next to strong continual-learning references rather than in isolation.",
  },
  {
    title: "Gretton et al. - MMD",
    citation: "Kernel two-sample testing for covariate shift.",
    usage:
      "MELD uses MMD-style drift signals to flag incoming distribution shift before or around the update, not only after the model has already moved.",
  },
];
